name: 'Setup SDL2 frameworks'
description: 'Install SDL2 frameworks in macOS GitHub Actions runners'
author: 'BrettDong'
inputs:
  dest:
    description: 'Installation destination'
    required: false
    default: '/Users/runner/Library/Frameworks'
  sdl2:
    description: 'SDL2 version'
    required: false
    default: 'none'
  sdl2-ttf:
    description: 'SDL2-ttf version'
    required: false
    default: 'none'
  sdl2-image:
    description: 'SDL2-image version'
    required: false
    default: 'none'
  sdl2-mixer:
    description: 'SDL2-mixer version'
    required: false
    default: 'none'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
